# homeworks
pb analysis 자체를 점검.


# loading

```{r}
is=readRDS("/data/kjc1/projects/#130.stroke/sobj/stroke_karo_SCT_integrated_QC_group3_day1_subclustering_25-07-03-09-32.rds")
is=subset(is, annotation2_big%in%unique(is$annotation2_big)[c(1,2,3,4,5,6,8)])

hc=readRDS("/data/SHW/38/pbmc_integrated.rds")
hc$type="hc"
hc=PercentageFeatureSet(hc, "^MT-",col.name="percent.mt")
hc=PercentageFeatureSet(hc, "^RPS|^RPL",col.name="percent.ribo")

tot=merge(is, hc)

```

# freq

## plot

### boxplot
```{r}
plot_cluster_fractions(is, "exp_sample_no", "annotation2_big", "g1")
plot_cluster_fractions(is, "exp_sample_no", "annotation2_detail", "g1")

plot_cluster_fractions(is, "exp_sample_no", "annotation2_big", "g10")
plot_cluster_fractions(is, "exp_sample_no", "annotation2_detail", "g10")

plot_cluster_fractions(tc4, "exp_sample_no", "CD4_T_Cell_sub", "g10")
# > names(is@meta.data)[142:151]
#  [1] "Monocyte_Macrophage_sub"    "CD4_T_Cell_sub"             "B_Cell_Lineage_sub"         "NK_Cell_sub"                "CD8_T_Cell_sub"            
#  [6] "Treg_sub"                   "Erythroid_sub"              "Dendritic_Cell_sub"         "T_Cell_Differentiated_sub"  "Megakaryocyte_Platelet_sub"
```

### cumulative bar graph
```{r}
cmb(is, "annotation2_big", "g1")
acmb(is, "annotation2_big", "g1")
cml(is, "annotation2_big", "g1")

cmb(is, "annotation2_detail", "g1")
acmb(is, "annotation2_detail", "g1")
cml(is, "annotation2_detail", "g1")
```

## stats
```{r}
seurat_group_stats(is,"exp_sample_no", "annotation2_big", "g1" )
seurat_group_stats(is,"exp_sample_no", "annotation2_detail", "g1" )
```

# DEGs
```{r}
library(DESeq2)
library(edgeR)
m1=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g1",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m2=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g2",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m3=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g3",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m4=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g4",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m5=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g5",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m6=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g6",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m7=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g7",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m8=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g8",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m9=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g9",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
m10=FindMarkers_pseudobulk(tc4,ident.1=2,ident.2 = 1,group.by = "g10",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3)%>%marker_filter()
ms=list(m1,m2,m3,m4,m5,m6,m7,m8,m9,m10)
# ms=lapply(ms, marker_filter)

tc4_g8=subset(tc4, cells=colnames(tc4)[!is.na(tc4$g8)])
m81=FindMarkers(tc4_g8, ident.1=2, group.by="g8")%>%marker_filter()
m82=FindMarkers_pseudobulk(tc4_g8,ident.1=2,ident.2 = 1,group.by = "g8",sample.by="exp_sample_no",assay = DefaultAssay(tc4), min.pct=0.3, method = "edgeR")%>%marker_filter()
m83 <- run_pseudobulk_deg(analysis_level = "overall",target_cluster = "CD4_T_Cell",contrast = c(-1, 1),seurat_obj = tc4_g8,assay = "SCT", slot = "counts",sample_col = "exp_sample_no", cluster_col = "annotation2_big", group_col = "g1")

cluster_pseudobulk_deg(tc4,
                                   "exp_sample_no",
                                   group.by = "g1",
                                   assay = DefaultAssay(tc4),
                                   layer = "data",
                                   slot = NULL,
                                   features = NULL,
                                   ident.1 = 2,
                                   ident.2 = 1,
                                   logfc.threshold = 0.1,
                                   test.use = "wilcox",
                                   min.pct = 0.1,
                                   min.diff.pct = -Inf,
                                   only.pos = FALSE,
                                   norm_method_edgeR = "TMM",
                                   min_count_edgeR = 10,
                                   p_adjust_method = "BH",
                                   verbose = TRUE)
```

#plots
```{r}
DotPlot(is2, ms[[2]]$gene[1:10], group.by="annotation2_big", split.by="g2", cols = c("red","blue","green"))
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

