#' Add Module Scores for a List of Feature Sets
#'
#' This function takes a Seurat object and a list of feature (gene) sets.
#' For each feature set, it calculates a module score using Seurat's AddModuleScore.
#' The name of the resulting metadata column will be the name of the feature set if provided,
#' or a concatenation of gene names joined by "+" if the feature set is unnamed.
#'
#' @param seurat_object A Seurat object.
#' @param feature_sets A named or unnamed list of character vectors. Each character vector is a set of gene names.
#'                     If the list is named, the names will be used for the output module score columns.
#'                     If a list element is unnamed, its name will be generated by concatenating gene names with "+".
#' @param assay Name of the assay to use. Default is the current default assay.
#' @param slot Slot to pull expression data from. Default is "data".
#' @param nbin Number of bins for AddModuleScore. Default is 24.
#' @param ctrl Number of control features for AddModuleScore. Default is 100.
#' @param seed Random seed for AddModuleScore. Default is 1.
#' @param search Passed to Seurat::`[.Assay`. Default is FALSE. Relevant if features are not present in the object.
#' @param ... Additional arguments passed to Seurat::AddModuleScore.
#'
#' @return A Seurat object with added module scores in the metadata.
#'
#' @examples
#' \dontrun{
#' # Assuming 'pbmc' is a Seurat object with an RNA assay
#' # Example feature sets
#' gene_sets <- list(
#'   Tcell_activation = c("CD69", "IFNG", "TNF"),
#'   Monocyte_markers = c("CD14", "LYZ"),
#'   c("CCR7", "SELL", "LEF1"), # Unnamed set
#'   Bcell_core = c("MS4A1", "CD19", "CD79A")
#' )
#'
#' pbmc <- AddMultipleModuleScores(seurat_object = pbmc, feature_sets = gene_sets)
#'
#' # Check the new metadata columns
#' head(pbmc@meta.data)
#'
#' # Visualize a score
#' FeaturePlot(pbmc, features = "Tcell_activation1") # Name is appended with a number
#' FeaturePlot(pbmc, features = "CCR7_SELL_LEF11")
#' }
AddMultipleModuleScores <- function(seurat_object,
                                    feature_sets,
                                    assay = NULL,
                                    slot = "data",
                                    nbin = 24,
                                    ctrl = 100,
                                    seed = 1,
                                    search = FALSE,
                                    ...) {
  
  if (!requireNamespace("Seurat", quietly = TRUE))
    stop("Package 'Seurat' is required but not installed.")
  if (!is.list(feature_sets))
    stop("'feature_sets' must be a list of character vectors.")
  
  if (is.null(assay))
    assay <- Seurat::DefaultAssay(seurat_object)
  
  all_genes <- rownames(Seurat::GetAssayData(seurat_object, assay = assay, slot = slot))
  added_cols <- character(0)              # <- 여기에 최종 컬럼명 모음
  
  for (i in seq_along(feature_sets)) {
    
    genes_raw <- feature_sets[[i]]
    genes_use <- intersect(genes_raw, all_genes)
    if (length(genes_use) == 0) {
      warning(sprintf("feature set %d: no genes found – skipped", i))
      next
    }
    
    set_name <- names(feature_sets)[i]
    if (is.null(set_name) || set_name == "")
      set_name <- paste(gsub("-", "_", genes_use), collapse = "+")
    
    #— 1) AddModuleScore 실행
    before_cols <- colnames(seurat_object[[]])
    seurat_object <- Seurat::AddModuleScore(
      object   = seurat_object,
      features = list(genes_use),
      name     = set_name,                # AddModuleScore가 set_name1 을 만듦
      assay    = assay,
      slot     = slot,
      nbin     = nbin,
      ctrl     = ctrl,
      seed     = seed,
      search   = search,
      ...
    )
    after_cols  <- colnames(seurat_object[[]])
    new_col     <- setdiff(after_cols, before_cols)  # 방금 생긴 컬럼
    
    #— 2) 뒤에 붙은 숫자 제거 & rename
    tidy_col    <- sub("1$", "", new_col)            # 끝의 1 지우기
    if (tidy_col != new_col) {
      colnames(seurat_object[[]])[match(new_col, after_cols)] <- tidy_col
      message(sprintf("renamed '%s' -> '%s'", new_col, tidy_col))
    }
    
    added_cols <- c(added_cols, tidy_col)
  }
  
  #— 3) FeaturePlot 에 바로 써먹을 수 있게 출력
  if (length(added_cols)) {
    msg1 <- "# Copy-&-paste for FeaturePlot:"
    msg2 <- sprintf("FeaturePlot(obj, features = c(%s))",
                    paste(sprintf("'%s'", added_cols), collapse=", "))
    message("\n", msg1, "\n", msg2, "\n")
    flush.console()
  } else {
    warning("No module scores were added.")
  }
  
  
  invisible(seurat_object)
}
