#' Gene list for myR analyses
#' https://azimuth.hubmapconsortium.org/references/human_pbmc/
#'
#' A character vector of default gene symbols.
#' @format A character vector of length 4.
#' @source Generated by package developer.
"genes_azi"

#' Gene list for myR analyses
#'
#' A character vector of default gene symbols.
#' @format A character vector of length 4.
#' @source Generated by package developer.
"genes_pbmc_new"

#' Gene list for myR analyses
#'
#' A character vector of default gene symbols.
#' @format A character vector of length 4.
#' @source Generated by package developer.
"genes_skin"